from debian

run apt-get update; apt-get upgrade; apt-get install -y curl git gpg
run curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
run curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg
run echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

run apt update && apt install -y yarn nodejs ffmpeg 

workdir /src

run mkdir auth
copy ./baileys-server/package.json /src/.
run yarn
copy ./baileys-server/index.ts /src/.

cmd [ "yarn", "build" ]